import './globals.css'
import type { Metadata } from 'next'
import TTHoves from './styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={TTHoves.className}>{children}</body>
    </html>
  )
}
